# Generated by Django 3.1.6 on 2021-02-17 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nameservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portals',
            },
        ),
        migrations.AlterModelOptions(
            name='nameservicemodel',
            options={'ordering': ['id'], 'verbose_name': 'SiaNS', 'verbose_name_plural': 'SiaNS'},
        ),
        migrations.CreateModel(
            name='UserPortalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal', to='nameservice.portalmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_portal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Portal',
                'verbose_name_plural': 'User Portal',
            },
        ),
    ]
