# Generated by Django 3.1.6 on 2021-02-17 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nameservice', '0002_auto_20210217_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportalmodel',
            name='portal',
            field=models.ForeignKey(help_text='Select Default Portal', on_delete=django.db.models.deletion.CASCADE, related_name='portal', to='nameservice.portalmodel'),
        ),
    ]
